### ISSUE TITLE
Email attachments create errors in viewing message stream

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#266]
Formatted error below: 

```
TypeError: Cannot read property 'email_id' of undefined
    at messages.map (/Users/kuanbutts/Documents/cfa/clientcomm/app/models/messages.js:402:31)
    at Array.map (native)
    at db.select.leftJoin.leftJoin.leftJoin.leftJoin.leftJoin.whereIn.orderBy.then.then (/Users/kuanbutts/Documents/cfa/clientcomm/app/models/messages.js:399:29)
    at wrapped (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at Promise.linkTransaction (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/newrelic/lib/instrumentation/promise.js:289:65)
    at Promise.wrapped [as __NR_wrapper] (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at __NR_wrappedThenHandler (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/newrelic/lib/instrumentation/promise.js:461:26)
    at tryCatcher (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/knex/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/knex/node_modules/bluebird/js/main/promise.js:581:18)
    at Async._drainQueue (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/knex/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at Immediate.wrapped (/Users/kuanbutts/Documents/cfa/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by kuanb** [comment]
Attachments getting returned in the messages model are list of `undefined` objects. 

```
[ undefined ]
```

Need to resolve at db query?
