### ISSUE TITLE
Transcript download errors when in case load view

### ISSUE THREAD

**Issue by kuanb** [slco-2016/clientcomm#267]
```
ReferenceError: reject is not defined
    at Function.findAllFromClient (/home/ubuntu/clientcomm/app/models/messages.js:274:14)
    at Users.findByClientId.then.then (/home/ubuntu/clientcomm/app/controllers/clients.js:442:25)
    at wrapped (/home/ubuntu/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at Promise.linkTransaction (/home/ubuntu/clientcomm/node_modules/newrelic/lib/instrumentation/promise.js:289:65)
    at Promise.wrapped (/home/ubuntu/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at Promise.proxyWrapper (/home/ubuntu/clientcomm/node_modules/newrelic/lib/instrumentation/promise.js:300:23)
    at __NR_wrappedThenHandler (/home/ubuntu/clientcomm/node_modules/newrelic/lib/instrumentation/promise.js:461:26)
    at tryCatcher (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/async.js:16:14)
    at Immediate.wrapped (/home/ubuntu/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by kuanb** [comment]
Cleared in production
