### ISSUE TITLE
creating a new primary user throws a ReferenceError

### ISSUE THREAD

**Issue by tmaybe** [slco-2016/clientcomm#379]
Submitting the form at `/org/users/create` as an owner-class user throws this error:

```
ReferenceError: html is not defined
    at Object.activationAlert (/home/ubuntu/clientcomm/app/lib/emailer.js:22:9)
    at Users.createOne.then (/home/ubuntu/clientcomm/app/controllers/users.js:67:22)
    at wrapped (/home/ubuntu/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at Promise.linkTransaction (/home/ubuntu/clientcomm/node_modules/newrelic/lib/instrumentation/promise.js:289:65)
    at Promise.wrapped [as __NR_wrapper] (/home/ubuntu/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at __NR_wrappedThenHandler (/home/ubuntu/clientcomm/node_modules/newrelic/lib/instrumentation/promise.js:461:26)
    at tryCatcher (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues (/home/ubuntu/clientcomm/node_modules/bluebird/js/release/async.js:16:14)
    at Immediate.wrapped (/home/ubuntu/clientcomm/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by tmaybe** [comment]
Fixed with 92b8f875786be4fdb50bc77066f55a3344fb2171
